version: "3"
services:
  jenkins-docker-centos:
    build:
      context: docker
      dockerfile: Dockerfile-centos
    image: aursu/jenkins:2.198-centos-docker-19.03.2-b1
  jenkins-docker:
    build:
      context: docker
    image: aursu/jenkins:2.198-docker-19.03.2-b1
  jenkins-cap-centos:
    volumes:
      - /share/jenkins:/var/jenkins_home
      - /share/deploy:/share/deploy
    build:
      context: .
      dockerfile: Dockerfile-centos
    image: aursu/jenkins:2.198-centos-cap-3.11.1-b1
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
  jenkins-cap:
    volumes:
      - /share/jenkins:/var/jenkins_home
      - /share/deploy:/share/deploy
    build:
      context: .
    image: aursu/jenkins:2.198-cap-3.11.1-b1
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
