FROM aursu/jenkins:2.203-centos-docker-19.03.4-b1

USER root

# Install ruby 2.5
RUN dnf -y install \
        gcc \
        make \
        ruby \
        ruby-devel \
    && dnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*

# upgrade rubygems
RUN gem update --system --no-document

# install Capistrano and another dependencies
RUN gem install --no-document --minimal-deps \
        capistrano:3.11.2 \
        bundler \
        capistrano-composer \
        capistrano-file-permissions \
        capistrano-harrow \
        capistrano-symfony \
        io-console

USER jenkins

# increase workers count to 5
COPY init.groovy.d/executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy
