version: "3"
services:
  jenkins-cap:
    volumes:
      - /share/jenkins:/var/jenkins_home
      - /share/deploy:/share/deploy
    build:
      context: .
    image: aursu/jenkins:2.195-centos-cap-3.11
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always
