FROM jenkins/jenkins:2.203-centos

ARG DOCKER_VERSION=19.03.4
ARG COMPOSE_VERSION=1.24.1

USER root

RUN dnf -y install \
		device-mapper-persistent-data \
		lvm2 \
		yum-utils \
	&& dnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*

RUN yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

RUN dnf -y install \
		docker-ce-cli-${DOCKER_VERSION} \
	&& dnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*

RUN curl \
	-L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m) \
	-o /usr/local/bin/docker-compose \
	&& chmod +x /usr/local/bin/docker-compose

USER jenkins
